require("plugins.autopairs")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.misc")
require("plugins.navic")
require("plugins.null-ls")
require("plugins.mini")
require("plugins.telescope")
require("plugins.treesitter")
-- require("plugins.toggleterm")
require("plugins.theme")
require("plugins.whichkey")
